import 'package:flutter_modular/flutter_modular.dart';
import 'package:new_ezagro_flutter/features/data/datasources/remote_datasource/farm_datasource/farm_plot_datasources/farm_plot_soil_stage_datasources/farm_plot_soil_stage_datasource.dart';
import 'package:new_ezagro_flutter/features/data/datasources/remote_datasource/farm_datasource/farm_plot_datasources/farm_plot_soil_stage_datasources/farm_plot_soil_stage_datasource_impl.dart';

import '../features/data/datasources/remote_datasource/agricultural_activity_datasources/agricultural_activity_datasource.dart';
import '../features/data/datasources/remote_datasource/agricultural_activity_datasources/agricultural_activity_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/agricultural_activity_datasources/agricultural_activity_type_datasources/agricultural_activity_type_datasource.dart';
import '../features/data/datasources/remote_datasource/agricultural_activity_datasources/agricultural_activity_type_datasources/agricultural_activity_type_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/agricultural_activity_datasources/agricultural_sub_activity_datasources/agricultural_sub_activity_datasource.dart';
import '../features/data/datasources/remote_datasource/agricultural_activity_datasources/agricultural_sub_activity_datasources/agricultural_sub_activity_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/agricultural_input_datasources/agricultural_input_class_datasources/agricultural_input_class_datasource.dart';
import '../features/data/datasources/remote_datasource/agricultural_input_datasources/agricultural_input_class_datasources/agricultural_input_class_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/agricultural_input_datasources/agricultural_input_datasource.dart';
import '../features/data/datasources/remote_datasource/agricultural_input_datasources/agricultural_input_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/authentication_datasource/authentication_datasource.dart';
import '../features/data/datasources/remote_datasource/authentication_datasource/authentication_datasources_impl.dart';
import '../features/data/datasources/remote_datasource/company_datasources/company_datasource.dart';
import '../features/data/datasources/remote_datasource/company_datasources/company_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/company_datasources/company_segment_datasources/company_segment_datasource.dart';
import '../features/data/datasources/remote_datasource/company_datasources/company_segment_datasources/company_segment_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/contract_datasources/contract_datasource.dart';
import '../features/data/datasources/remote_datasource/contract_datasources/contract_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/cost_center_datasource/cost_center_datasource.dart';
import '../features/data/datasources/remote_datasource/cost_center_datasource/cost_center_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/crop_datasources/crop_datasource.dart';
import '../features/data/datasources/remote_datasource/crop_datasources/crop_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/crop_datasources/crop_variety_datasources/crop_variety_datasource.dart';
import '../features/data/datasources/remote_datasource/crop_datasources/crop_variety_datasources/crop_variety_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/employee_datasources/employee_datasource.dart';
import '../features/data/datasources/remote_datasource/employee_datasources/employee_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/executors_datasources/executors_datasource.dart';
import '../features/data/datasources/remote_datasource/executors_datasources/executors_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/farm_datasource/farm_datasource.dart';
import '../features/data/datasources/remote_datasource/farm_datasource/farm_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/farm_datasource/farm_plot_datasources/farm_plot_datasource.dart';
import '../features/data/datasources/remote_datasource/farm_datasource/farm_plot_datasources/farm_plot_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/machinery_implement_datasources/machinery_implement_datasource.dart';
import '../features/data/datasources/remote_datasource/machinery_implement_datasources/machinery_implement_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/payment_method_datasources/payment_method_datasource.dart';
import '../features/data/datasources/remote_datasource/payment_method_datasources/payment_method_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/pest_datasources/pest_datasource.dart';
import '../features/data/datasources/remote_datasource/pest_datasources/pest_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/plots_datasource/plots_datasource.dart';
import '../features/data/datasources/remote_datasource/plots_datasource/plots_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/product_datasources/product_datasource.dart';
import '../features/data/datasources/remote_datasource/product_datasources/product_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/product_datasources/product_type_datasources/product_type_datasource.dart';
import '../features/data/datasources/remote_datasource/product_datasources/product_type_datasources/product_type_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/purchase_request_datasources/purchase_request_datasource.dart';
import '../features/data/datasources/remote_datasource/purchase_request_datasources/purchase_request_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/purchase_request_datasources/purchase_request_delivery_location_datasources/purchase_request_delivery_location_datasource.dart';
import '../features/data/datasources/remote_datasource/purchase_request_datasources/purchase_request_delivery_location_datasources/purchase_request_delivery_location_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/purchase_request_datasources/purchase_request_type_datasource/purchase_request_type_datasource.dart';
import '../features/data/datasources/remote_datasource/purchase_request_datasources/purchase_request_type_datasource/purchase_request_type_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/service_order_datasources/service_order_datasource.dart';
import '../features/data/datasources/remote_datasource/service_order_datasources/service_order_datasource_impl.dart';
import '../features/data/datasources/remote_datasource/user_datasources/user_datasource.dart';
import '../features/data/datasources/remote_datasource/user_datasources/user_datasource_impl.dart';

class DatasourceBinds {

  void binds(Injector i) {
    i.addLazySingleton<AuthenticationDatasource>(AuthenticationDatasourceImpl.new);
    i.addLazySingleton<ServiceOrderDatasource>(ServiceOrderDatasourceImpl.new);
    i.addLazySingleton<AgriculturalActivityDatasource>(AgriculturalActivityDatasourceImpl.new);
    i.addLazySingleton<AgriculturalInputDatasource>(AgriculturalInputDatasourceImpl.new);
    i.addLazySingleton<AgriculturalInputClassDatasource>(AgriculturalInputClassDatasourceImpl.new);
    i.addLazySingleton<AgriculturalSubActivityDatasource>(AgriculturalSubActivityDatasourceImpl.new);
    i.addLazySingleton<CostCenterDatasource>(CostCenterDatasourceImpl.new);
    i.addLazySingleton<FarmDatasource>(FarmDatasourceImpl.new);
    i.addLazySingleton<FarmPlotDatasource>(FarmPlotDatasourceImpl.new);
    i.addLazySingleton<FarmPlotSoilStageDatasource>(FarmPlotSoilStageDatasourceImpl.new);
    i.addLazySingleton<CropDatasource>(CropDatasourceImpl.new);
    i.addLazySingleton<CropVarietyDatasource>(CropVarietyDatasourceImpl.new);
    i.addLazySingleton<PlotsDatasource>(PlotsDatasourceImpl.new);
    i.addLazySingleton<ExecutorsDatasource>(ExecutorsDatasourceImpl.new);
    i.addLazySingleton<MachineryImplementDatasource>(MachineryImplementDatasourceImpl.new);
    i.addLazySingleton<EmployeeDatasource>(EmployeeDatasourceImpl.new);
    i.addLazySingleton<PestDatasource>(PestDatasourceImpl.new);
    i.addLazySingleton<UserDatasource>(UserDatasourceImpl.new);
    i.addLazySingleton<CompanyDatasource>(CompanyDatasourceImpl.new);
    i.addLazySingleton<CompanySegmentDatasource>(CompanySegmentDatasourceImpl.new);
    i.addLazySingleton<ContractDatasource>(ContractDatasourceImpl.new);
    i.addLazySingleton<PaymentMethodDatasource>(PaymentMethodDatasourceImpl.new);
    i.addLazySingleton<ProductDatasource>(ProductDatasourceImpl.new);
    i.addLazySingleton<ProductTypeDatasource>(ProductTypeDatasourceImpl.new);
    i.addLazySingleton<PurchaseRequestDatasource>(PurchaseRequestDatasourceImpl.new);
    i.addLazySingleton<PurchaseRequestTypeDatasource>(PurchaseRequestTypeDatasourceImpl.new);
    i.addLazySingleton<PurchaseRequestDeliveryLocationDatasource>(PurchaseRequestDeliveryLocationDatasourceImpl.new);
    i.addLazySingleton<AgriculturalActivityTypeDatasource>(AgriculturalActivityTypeDatasourceImpl.new);
  }
}