import 'package:flutter_modular/flutter_modular.dart';
import 'package:new_ezagro_flutter/features/data/repositories/farm_repositories/farm_plot_repositories/farm_plot_soil_stage_repositores/farm_plot_soil_stage_repository_impl.dart';
import 'package:new_ezagro_flutter/features/domain/repositories/farm_repositories/farm_plot_repositories/farm_plot_soil_stage_repositores/farm_plot_soil_stage_repository.dart';

import '../features/data/repositories/agricultural_activity_repositories/agricultural_activity_repository_impl.dart';
import '../features/data/repositories/agricultural_activity_repositories/agricultural_activity_type_repositories/agricultural_activity_type_respository_impl.dart';
import '../features/data/repositories/agricultural_activity_repositories/agricultural_sub_activity_repositories/agricultural_sub_activity_repository_impl.dart';
import '../features/data/repositories/agricultural_input_repositories/agricultural_input_class_repositories/agricultural_input_class_repository_impl.dart';
import '../features/data/repositories/agricultural_input_repositories/agricultural_input_repository_impl.dart';
import '../features/data/repositories/authentication_repository/authentication_repository_impl.dart';
import '../features/data/repositories/company_repositories/company_repository_impl.dart';
import '../features/data/repositories/company_repositories/company_segment_repository/company_segment_repository_impl.dart';
import '../features/data/repositories/contract_repositories/contract_repository_impl.dart';
import '../features/data/repositories/cost_center_repositories/cost_center_repository_impl.dart';
import '../features/data/repositories/crop_repositories/crop_repository_impl.dart';
import '../features/data/repositories/crop_repositories/crop_variety_repositories/crop_variety_repository_impl.dart';
import '../features/data/repositories/employee_repositories/employee_repository_impl.dart';
import '../features/data/repositories/executors_repositories/executors_repository_impl.dart';
import '../features/data/repositories/farm_repositories/farm_plot_repositories/farm_plot_repository_impl.dart';
import '../features/data/repositories/farm_repositories/farm_repository_impl.dart';
import '../features/data/repositories/machinery_implement_repositories/machinery_implement_repository_impl.dart';
import '../features/data/repositories/payment_method_repositories/payment_method_repository_impl.dart';
import '../features/data/repositories/pest_repositories/pest_repository_impl.dart';
import '../features/data/repositories/plots_repositories/plots_repository_impl.dart';
import '../features/data/repositories/products_repositories/product_type_repositories/product_type_repository_impl.dart';
import '../features/data/repositories/products_repositories/products_repository_impl.dart';
import '../features/data/repositories/purchase_request_repositories/purchase_request_delivery_location_repositories/purchase_request_delivery_location_repository_impl.dart';
import '../features/data/repositories/purchase_request_repositories/purchase_request_repository_impl.dart';
import '../features/data/repositories/purchase_request_repositories/purchase_request_type_repository/purchase_request_type_repository_impl.dart';
import '../features/data/repositories/service_order_repositories/service_order_repository_impl.dart';
import '../features/data/repositories/user_repositories/user_repository_impl.dart';
import '../features/domain/repositories/agricultural_activity_repositories/agricultural_activity_repository.dart';
import '../features/domain/repositories/agricultural_activity_repositories/agricultural_activity_type_repositories/agricultural_activity_type_respository.dart';
import '../features/domain/repositories/agricultural_activity_repositories/agricultural_sub_activity_repositories/agricultural_sub_activity_repository.dart';
import '../features/domain/repositories/agricultural_input_repositories/agricultural_input_class_repositories/agricultural_input_class_repository.dart';
import '../features/domain/repositories/agricultural_input_repositories/agricultural_input_repository.dart';
import '../features/domain/repositories/authentication_repository/authentication_repository.dart';
import '../features/domain/repositories/company_repositories/company_repository.dart';
import '../features/domain/repositories/company_repositories/company_segment_repository/company_segment_repository.dart';
import '../features/domain/repositories/contract_repositories/contract_repository.dart';
import '../features/domain/repositories/cost_center_repositories/cost_center_repository.dart';
import '../features/domain/repositories/crop_repositories/crop_repository.dart';
import '../features/domain/repositories/crop_repositories/crop_variety_repositories/crop_variety_repository.dart';
import '../features/domain/repositories/employee_repositories/employee_repository.dart';
import '../features/domain/repositories/executors_repositories/executors_repository.dart';
import '../features/domain/repositories/farm_repositories/farm_plot_repositories/farm_plot_repository.dart';
import '../features/domain/repositories/farm_repositories/farm_repository.dart';
import '../features/domain/repositories/machinery_implement_repositories/machinery_implement_repository.dart';
import '../features/domain/repositories/payment_method_repositories/payment_method_repository.dart';
import '../features/domain/repositories/pest_repositories/pest_repository.dart';
import '../features/domain/repositories/plots_repositories/plots_repository.dart';
import '../features/domain/repositories/product_repositories/product_repository.dart';
import '../features/domain/repositories/product_repositories/product_type_repositories/product_type_repository.dart';
import '../features/domain/repositories/purchase_request_repositories/purchase_request_delivery_location_repositories/purchase_request_delivery_location_repository.dart';
import '../features/domain/repositories/purchase_request_repositories/purchase_request_repository.dart';
import '../features/domain/repositories/purchase_request_repositories/purchase_request_type_repository/purchase_request_type_repository.dart';
import '../features/domain/repositories/service_order_repositories/service_order_repository.dart';
import '../features/domain/repositories/user_repositories/user_repository.dart';

class RepositoryBinds {
  void binds(Injector i) {
    i.addLazySingleton<AuthenticationRepository>(AuthenticationRepositoryImpl.new);
    i.addLazySingleton<ServiceOrderRepository>(ServiceOrderRepositoryImpl.new);
    i.addLazySingleton<AgriculturalActivityRepository>(AgriculturalActivityRepositoryImpl.new);
    i.addLazySingleton<AgriculturalInputRepository>(AgriculturalInputRepositoryImpl.new);
    i.addLazySingleton<AgriculturalInputClassRepository>(AgriculturalInputClassRepositoryImpl.new);
    i.addLazySingleton<AgriculturalSubActivityRepository>(AgriculturalSubActivityRepositoryImpl.new);
    i.addLazySingleton<CostCenterRepository>(CostCenterRepositoryImpl.new);
    i.addLazySingleton<FarmRepository>(FarmRepositoryImpl.new);
    i.addLazySingleton<FarmPlotRepository>(FarmPlotRepositoryImpl.new);
    i.addLazySingleton<FarmPlotSoilStageRepository>(FarmPlotSoilStageRepositoryImpl.new);
    i.addLazySingleton<CropRepository>(CropRepositoryImpl.new);
    i.addLazySingleton<CropVarietyRepository>(CropVarietyRepositoryImpl.new);
    i.addLazySingleton<PlotsRepository>(PlotsRepositoryImpl.new);
    i.addLazySingleton<ExecutorsRepository>(ExecutorsRepositoryImpl.new);
    i.addLazySingleton<MachineryImplementRepository>(MachineryImplementRepositoryImpl.new);
    i.addLazySingleton<ProductRepository>(ProductRepositoryImpl.new);
    i.addLazySingleton<ProductTypeRepository>(ProductTypeRepositoryImpl.new);
    i.addLazySingleton<EmployeeRepository>(EmployeeRepositoryImpl.new);
    i.addLazySingleton<PestRepository>(PestRepositoryImpl.new);
    i.addLazySingleton<UserRepository>(UserRepositoryImpl.new);
    i.addLazySingleton<CompanyRepository>(CompanyRepositoryImpl.new);
    i.addLazySingleton<CompanySegmentRepository>(CompanySegmentRepositoryImpl.new);
    i.addLazySingleton<ContractRepository>(ContractRepositoryImpl.new);
    i.addLazySingleton<PaymentMethodRepository>(PaymentMethodRepositoryImpl.new);
    i.addLazySingleton<AgriculturalActivityTypeRepository>(AgriculturalActivityTypeRepositoryImpl.new);
    i.addLazySingleton<PurchaseRequestRepository>(PurchaseRequestRepositoryImpl.new);
    i.addLazySingleton<PurchaseRequestTypeRepository>(PurchaseRequestTypeRepositoryImpl.new);
    i.addLazySingleton<PurchaseRequestDeliveryLocationRepository>(PurchaseRequestDeliveryLocationRepositoryImpl.new);
  }
}