import 'package:flutter_modular/flutter_modular.dart';

import '../features/domain/usecases/agricultural_activity_usecases/get_all_agricultural_activities_usecases/get_all_agricultural_activities_usecase.dart';
import '../features/domain/usecases/agricultural_activity_usecases/get_all_agricultural_activities_usecases/get_all_agricultural_activities_usecase_impl.dart';
import '../features/domain/usecases/authentication_usecases/authenticate_usecase/authenticate_usecase.dart';
import '../features/domain/usecases/authentication_usecases/authenticate_usecase/authenticate_usecase_impl.dart';
import '../features/domain/usecases/authentication_usecases/recover_password_usecase/recover_password_usecase.dart';
import '../features/domain/usecases/authentication_usecases/recover_password_usecase/recover_password_usecase_impl.dart';
import '../features/domain/usecases/authentication_usecases/update_password/update_password_usecase.dart';
import '../features/domain/usecases/authentication_usecases/update_password/update_password_usecase_impl.dart';
import '../features/domain/usecases/company_usecases/get_all_companies_to_select_usecase/get_all_companies_to_select_usecase.dart';
import '../features/domain/usecases/company_usecases/get_all_companies_to_select_usecase/get_all_companies_to_select_usecase_impl.dart';
import '../features/domain/usecases/company_usecases/get_all_companies_usecase/get_all_companies_usecase.dart';
import '../features/domain/usecases/company_usecases/get_all_companies_usecase/get_all_companies_usecase_impl.dart';
import '../features/domain/usecases/company_usecases/get_company_by_id_usecase/get_company_by_id_usecase.dart';
import '../features/domain/usecases/company_usecases/get_company_by_id_usecase/get_company_by_id_usecase_impl.dart';
import '../features/domain/usecases/contract_usecases/get_contract_by_id_usecase/get_contract_by_id_usecase.dart';
import '../features/domain/usecases/contract_usecases/get_contract_by_id_usecase/get_contract_by_id_usecase_impl.dart';
import '../features/domain/usecases/contract_usecases/get_contract_list_usecase/get_contract_list_usecase.dart';
import '../features/domain/usecases/contract_usecases/get_contract_list_usecase/get_contract_list_usecase_impl.dart';
import '../features/domain/usecases/cost_center_usecases/get_all_cost_center_to_select_impl.dart';
import '../features/domain/usecases/cost_center_usecases/get_all_cost_center_to_select_usecase.dart';
import '../features/domain/usecases/crop_usecases/crop_usecase.dart';
import '../features/domain/usecases/crop_usecases/crop_usecase_impl.dart';
import '../features/domain/usecases/employee_usecase/employee_usecase.dart';
import '../features/domain/usecases/employee_usecase/employee_usecase_impl.dart';
import '../features/domain/usecases/employee_usecase/get_employee_by_id_usecase/get_employee_by_id_usecase.dart';
import '../features/domain/usecases/employee_usecase/get_employee_by_id_usecase/get_employee_by_id_usecase_impl.dart';
import '../features/domain/usecases/employee_usecase/get_employee_list_usecase/get_employee_list_usecase.dart';
import '../features/domain/usecases/employee_usecase/get_employee_list_usecase/get_employee_list_usecase_impl.dart';
import '../features/domain/usecases/executor_usecases/executor_usecase.dart';
import '../features/domain/usecases/executor_usecases/executor_usecase_impl.dart';
import '../features/domain/usecases/farm_usecases/farm_usecase.dart';
import '../features/domain/usecases/farm_usecases/farm_usecase_impl.dart';
import '../features/domain/usecases/farm_usecases/get_all_farms_by_cost_center_id_to_select_usecases/get_all_farms_by_cost_center_id_to_select_usecase.dart';
import '../features/domain/usecases/farm_usecases/get_all_farms_by_cost_center_id_to_select_usecases/get_all_farms_by_cost_center_id_to_select_usecase_impl.dart';
import '../features/domain/usecases/farm_usecases/get_farm_by_id_usecase/get_farm_by_id_usecase.dart';
import '../features/domain/usecases/farm_usecases/get_farm_by_id_usecase/get_farm_by_id_usecase_impl.dart';
import '../features/domain/usecases/farm_usecases/get_farm_list_usecase/get_farm_list_usecase.dart';
import '../features/domain/usecases/farm_usecases/get_farm_list_usecase/get_farm_list_usecase_impl.dart';
import '../features/domain/usecases/farm_usecases/get_farms_by_cost_center_id_usecases/get_farms_by_cost_center_id_usecase.dart';
import '../features/domain/usecases/farm_usecases/get_farms_by_cost_center_id_usecases/get_farms_by_cost_center_id_usecase_impl.dart';
import '../features/domain/usecases/machinery_usecases/get_all_machinery_usecases/get_all_machinery_usecase.dart';
import '../features/domain/usecases/machinery_usecases/get_all_machinery_usecases/get_all_machinery_usecase_impl.dart';
import '../features/domain/usecases/machinery_usecases/get_machinery_implement_by_id/get_machinery_implement_by_id_usecase.dart';
import '../features/domain/usecases/machinery_usecases/get_machinery_implement_by_id/get_machinery_implement_by_id_usecase_impl.dart';
import '../features/domain/usecases/machinery_usecases/machinery_usecase.dart';
import '../features/domain/usecases/machinery_usecases/machinery_usecase_impl.dart';
import '../features/domain/usecases/pest_usecases/pest_usecase.dart';
import '../features/domain/usecases/pest_usecases/pest_usecase_impl.dart';
import '../features/domain/usecases/plots_usecases/plots_usecase.dart';
import '../features/domain/usecases/plots_usecases/plots_usecase_impl.dart';
import '../features/domain/usecases/plots_usecases/plots_with_farm_id_usecase.dart';
import '../features/domain/usecases/plots_usecases/plots_with_farm_id_usecase_impl.dart';
import '../features/domain/usecases/product_usecases/get_all_products_usecase/get_all_products_usecase.dart';
import '../features/domain/usecases/product_usecases/get_all_products_usecase/get_all_products_usecase_impl.dart';
import '../features/domain/usecases/purchase_request_usecases/approve_purchase_request_by_id_usecases/approve_purchase_request_by_id_usecase.dart';
import '../features/domain/usecases/purchase_request_usecases/approve_purchase_request_by_id_usecases/approve_purchase_request_by_id_usecase_impl.dart';
import '../features/domain/usecases/purchase_request_usecases/cancel_purchase_request_by_id_usecases/cancel_purchase_request_by_id_usecase.dart';
import '../features/domain/usecases/purchase_request_usecases/cancel_purchase_request_by_id_usecases/cancel_purchase_request_by_id_usecase_impl.dart';
import '../features/domain/usecases/purchase_request_usecases/get_all_purchase_request_type_to_select_usecase/get_all_purchase_request_type_to_select_usecase.dart';
import '../features/domain/usecases/purchase_request_usecases/get_all_purchase_request_type_to_select_usecase/get_all_purchase_request_type_to_select_usecase_impl.dart';
import '../features/domain/usecases/purchase_request_usecases/get_all_purchase_request_usecases/get_all_purchase_request_usecase.dart';
import '../features/domain/usecases/purchase_request_usecases/get_all_purchase_request_usecases/get_all_purchase_request_usecase_impl.dart';
import '../features/domain/usecases/purchase_request_usecases/get_purchase_request_by_id_usecases/get_purchase_request_by_id_usecase.dart';
import '../features/domain/usecases/purchase_request_usecases/get_purchase_request_by_id_usecases/get_purchase_request_by_id_usecase_impl.dart';
import '../features/domain/usecases/purchase_request_usecases/get_purchase_request_by_status_id_usecases/get_purchase_request_by_status_id_usecase.dart';
import '../features/domain/usecases/purchase_request_usecases/get_purchase_request_by_status_id_usecases/get_purchase_request_by_status_id_usecases_impl.dart';
import '../features/domain/usecases/service_order_usecase/approve_service_order_by_id_usecase/approve_service_order_by_id_usecase.dart';
import '../features/domain/usecases/service_order_usecase/approve_service_order_by_id_usecase/approve_service_order_by_id_usecase_impl.dart';
import '../features/domain/usecases/service_order_usecase/cancel_service_order_by_id_usecase/cancel_service_order_by_id_usecase.dart';
import '../features/domain/usecases/service_order_usecase/cancel_service_order_by_id_usecase/cancel_service_order_by_id_usecase_impl.dart';
import '../features/domain/usecases/service_order_usecase/create_service_order_usecase.dart';
import '../features/domain/usecases/service_order_usecase/create_service_order_usecase_impl.dart';
import '../features/domain/usecases/service_order_usecase/get_service_order_by_id_usecase.dart';
import '../features/domain/usecases/service_order_usecase/get_service_order_by_id_usecase_impl.dart';
import '../features/domain/usecases/service_order_usecase/get_service_order_by_status_id_usecase/get_service_order_by_status_id_usecase.dart';
import '../features/domain/usecases/service_order_usecase/get_service_order_by_status_id_usecase/get_service_order_by_status_id_usecase_impl.dart';
import '../features/domain/usecases/service_order_usecase/service_order_list_usecase.dart';
import '../features/domain/usecases/service_order_usecase/service_order_list_usecase_impl.dart';
import '../features/domain/usecases/user_usecases/get_all_users_usecases/get_all_users_usecase.dart';
import '../features/domain/usecases/user_usecases/get_all_users_usecases/get_all_users_usecase_impl.dart';
import '../features/domain/usecases/user_usecases/get_user_by_id_usecase/get_user_by_id_usecase.dart';
import '../features/domain/usecases/user_usecases/get_user_by_id_usecase/get_user_by_id_usecase_impl.dart';
import '../features/domain/usecases/user_usecases/update_user_by_id_usecase/update_user_by_id_usecase.dart';
import '../features/domain/usecases/user_usecases/update_user_by_id_usecase/update_user_by_id_usecase_impl.dart';

class UsecaseBinds {
  void binds(Injector i) {
    i.addLazySingleton<AuthenticateUsecase>(AuthenticateUsecaseImpl.new);
    i.addLazySingleton<RecoverPasswordUsecase>(RecoverPasswordUsecaseImpl.new);
    i.addLazySingleton<UpdatePasswordUsecase>(UpdatePasswordUsecaseImpl.new);
    i.addLazySingleton<ServiceOrderListUsecase>(ServiceOrderListUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalActivitiesUsecase>(GetAllAgriculturalActivitiesUsecaseImpl.new);

    i.addLazySingleton<GetAllCostCenterToSelectUsecase>(GetAllCostCenterToSelectUsecaseImpl.new);
    i.addLazySingleton<FarmUsecase>(FarmUsecaseImpl.new);
    i.addLazySingleton<CropUsecase>(CropUsecaseImpl.new);
    i.addLazySingleton<PlotsUsecase>(PlotsUsecaseImpl.new);
    i.addLazySingleton<ExecutorUsecase>(ExecutorUsecaseImpl.new);
    i.addLazySingleton<MachineryUsecase>(MachineryUsecaseImpl.new);
    i.addLazySingleton<GetAllProductsUsecase>(GetAllProductsUsecaseImpl.new);
    i.addLazySingleton<EmployeeUsecase>(EmployeeUsecaseImpl.new);
    i.addLazySingleton<CreateServiceOrderUsecase>(CreateServiceOrderUsecaseImpl.new);
    i.addLazySingleton<GetServiceOrderByIdUsecase>(GetServiceOrderByIdUsecaseImpl.new);
    i.addLazySingleton<GetServiceOrderByStatusIdUsecase>(GetServiceOrderByStatusIdUsecaseImpl.new);

    i.addLazySingleton<GetAllPurchaseRequestUsecase>(GetAllPurchaseRequestUsecaseImpl.new);
    i.addLazySingleton<GetAllPurchaseRequestTypeToSelectUsecase>(GetAllPurchaseRequestTypeToSelectUsecaseImpl.new);
    i.addLazySingleton<GetPurchaseRequestByIdUsecase>(GetPurchaseRequestByIdUsecaseImpl.new);
    i.addLazySingleton<ApprovePurchaseRequestByIdUsecase>(ApprovePurchaseRequestByIdUsecaseImpl.new);
    i.addLazySingleton<CancelPurchaseRequestByIdUsecase>(CancelPurchaseRequestByIdUsecaseImpl.new);
    i.addLazySingleton<GetPurchaseRequestByStatusIdUsecase>(GetPurchaseRequestByStatusIdUsecaseImpl.new);

    i.addLazySingleton<ApproveServiceOrderByIdUsecase>(ApproveServiceOrderByIdUsecaseImpl.new);
    i.addLazySingleton<CancelServiceOrderByIdUsecase>(CancelServiceOrderByIdUsecaseImpl.new);

    i.addLazySingleton<PestUsecase>(PestUsecaseImpl.new);
    i.addLazySingleton<GetFarmsByCostCenterIdUsecase>(GetFarmsByCostCenterIdUsecaseImpl.new);
    i.addLazySingleton<GetAllFarmsByCostCenterIdToSelectUsecase>(GetAllFarmsByCostCenterIdToSelectUsecaseImpl.new);
    i.addLazySingleton<PlotsWithFarmIdUsecase>(PlotsWithFarmIdUsecaseImpl.new);
    i.addLazySingleton<GetFarmByIdUsecase>(GetFarmByIdUsecaseImpl.new);

    i.addLazySingleton<GetAllUsersUsecase>(GetAllUsersUsecaseImpl.new);
    i.addLazySingleton<GetAllMachineryUsecase>(GetAllMachineryUsecaseImpl.new);
    i.addLazySingleton<GetMachineryImplementByIdUsecase>(GetMachineryImplementByIdUsecaseImpl.new);
    i.addLazySingleton<GetUserByIdUsecase>(GetUserByIdUsecaseImpl.new);
    i.addLazySingleton<UpdateUserByIdUsecase>(UpdateUserByIdUsecaseImpl.new);
    i.addLazySingleton<GetAllCompaniesUsecase>(GetAllCompaniesUsecaseImpl.new);
    i.addLazySingleton<GetAllCompaniesToSelectUsecase>(GetAllCompaniesToSelectUsecaseImpl.new);
    i.addLazySingleton<GetCompanyByIdUsecase>(GetCompanyByIdUsecaseImpl.new);
    i.addLazySingleton<GetFarmListUsecase>(GetFarmListUsecaseImpl.new);
    i.addLazySingleton<GetEmployeeListUsecase>(GetEmployeeListUsecaseImpl.new);
    i.addLazySingleton<GetEmployeeByIdUsecase>(GetEmployeeByIdUsecaseImpl.new);
    i.addLazySingleton<GetContractListUsecase>(GetContractListUsecaseImpl.new);
    i.addLazySingleton<GetContractByIdUsecase>(GetContractByIdUsecaseImpl.new);
  }
}