import 'package:flutter_modular/flutter_modular.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/agricultural_activity_type_usecases/get_agricultural_activity_type_by_id_usecases/get_agricultural_activity_type_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/agricultural_activity_type_usecases/get_agricultural_activity_type_by_id_usecases/get_agricultural_activity_type_by_id_usecases_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/agricultural_activity_type_usecases/get_all_agricultural_activity_types_to_select_usecases/get_all_agricultural_activity_types_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/agricultural_activity_type_usecases/get_all_agricultural_activity_types_to_select_usecases/get_all_agricultural_activity_types_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/agricultural_activity_type_usecases/get_all_agricultural_activity_types_usecases/get_all_agricultural_activity_types_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/agricultural_sub_activitiy_usecases/get_agricultural_sub_activity_by_id_usecases/get_agricultural_sub_activity_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/agricultural_sub_activitiy_usecases/get_agricultural_sub_activity_by_id_usecases/get_agricultural_sub_activity_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/agricultural_sub_activitiy_usecases/get_all_agricultural_sub_activities_by_activity_id_to_select_usecases/get_all_agricultural_sub_activities_by_activity_id_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/agricultural_sub_activitiy_usecases/get_all_agricultural_sub_activities_by_activity_id_to_select_usecases/get_all_agricultural_sub_activities_by_activity_id_to_select_usecases_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/agricultural_sub_activitiy_usecases/get_all_agricultural_sub_activities_usecases/get_all_agricultural_sub_activities_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/agricultural_sub_activitiy_usecases/get_all_agricultural_sub_activities_usecases/get_all_agricultural_sub_activities_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/get_all_agricultural_activities_to_select_usecases/get_all_agricultural_activities_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/get_all_agricultural_activities_to_select_usecases/get_all_agricultural_activities_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/get_all_agricultural_activities_usecases/get_all_agricultural_activities_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/get_all_agricultural_activity_by_type_id_to_select_usecases/get_all_agricultural_activity_by_type_id_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/get_all_agricultural_activity_by_type_id_usecases/get_all_agricultural_activity_by_type_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_activity_usecases/get_all_agricultural_activity_by_type_id_usecases/get_all_agricultural_activity_by_type_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/agricultural_input_class_usecases/get_agricultural_class_by_id_usecases/get_agricultural_class_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/agricultural_input_class_usecases/get_agricultural_class_by_id_usecases/get_agricultural_class_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/agricultural_input_class_usecases/get_all_agricultural_classes_usecases/get_all_agricultural_input_classes_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/agricultural_input_class_usecases/get_all_agricultural_classes_usecases/get_all_agricultural_input_classes_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/agricultural_input_class_usecases/get_all_agricultural_input_classes_to_select_usecases/get_all_agricultural_input_classes_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/agricultural_input_class_usecases/get_all_agricultural_input_classes_to_select_usecases/get_all_agricultural_input_classes_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/get_agricultural_input_by_id_usecases/get_agricultural_input_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/get_agricultural_input_by_id_usecases/get_agricultural_input_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/get_all_agricultural_inputs_by_class_id_to_select_usecases/get_all_agricultural_inputs_by_class_id_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/get_all_agricultural_inputs_by_class_id_to_select_usecases/get_all_agricultural_inputs_by_class_id_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/get_all_agricultural_inputs_by_class_id_usecases/get_all_agricultural_inputs_by_class_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/get_all_agricultural_inputs_by_class_id_usecases/get_all_agricultural_inputs_by_class_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/get_all_agricultural_inputs_to_select_usecases/get_all_agricultural_inputs_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/get_all_agricultural_inputs_to_select_usecases/get_all_agricultural_inputs_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/get_all_agricultural_inputs_usecases/get_all_agricultural_inputs_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/agricultural_input_usecases/get_all_agricultural_inputs_usecases/get_all_agricultural_inputs_usecases_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/authentication_usecases/authenticate_usecase/authenticate_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/authentication_usecases/authenticate_usecase/authenticate_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/authentication_usecases/recover_password_usecase/recover_password_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/authentication_usecases/recover_password_usecase/recover_password_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/authentication_usecases/update_password/update_password_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/authentication_usecases/update_password/update_password_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/company_segment_usecases/get_all_company_segments_to_select_usecases/get_all_company_segments_to_select_usecases.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/company_segment_usecases/get_all_company_segments_to_select_usecases/get_all_company_segments_to_select_usecases_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/company_segment_usecases/get_all_company_segments_usecases/get_all_company_segments_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/company_segment_usecases/get_all_company_segments_usecases/get_all_company_segments_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/company_segment_usecases/get_company_segment_by_id_usecases/get_company_segment_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/company_segment_usecases/get_company_segment_by_id_usecases/get_company_segment_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/get_all_companies_to_select_usecase/get_all_companies_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/get_all_companies_to_select_usecase/get_all_companies_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/get_all_companies_usecase/get_all_companies_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/get_all_companies_usecase/get_all_companies_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/get_company_by_id_usecase/get_company_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/get_company_by_id_usecase/get_company_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/contract_usecases/get_all_contracts_to_select_usecases/get_all_contracts_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/contract_usecases/get_all_contracts_to_select_usecases/get_all_contracts_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/contract_usecases/get_all_contracts_usecases/get_all_contracts_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/contract_usecases/get_all_contracts_usecases/get_all_contracts_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/contract_usecases/get_contract_by_id_usecase/get_contract_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/contract_usecases/get_contract_by_id_usecase/get_contract_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/cost_center_usecases/get_all_cost_centers_by_cost_center_type_id_to_select_usecases/get_all_cost_centers_by_cost_center_type_id_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/cost_center_usecases/get_all_cost_centers_by_cost_center_type_id_to_select_usecases/get_all_cost_centers_by_cost_center_type_id_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/cost_center_usecases/get_all_cost_centers_by_cost_center_type_id_usecases/get_all_cost_centers_by_cost_center_type_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/cost_center_usecases/get_all_cost_centers_by_cost_center_type_id_usecases/get_all_cost_centers_by_cost_center_type_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/cost_center_usecases/get_all_cost_centers_to_select_usecases/get_all_cost_centers_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/cost_center_usecases/get_all_cost_centers_usecases/get_all_cost_centers_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/cost_center_usecases/get_all_cost_centers_usecases/get_all_cost_centers_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/cost_center_usecases/get_cost_center_by_id_usecases/get_cost_center_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/cost_center_usecases/get_cost_center_by_id_usecases/get_cost_center_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/crop_variety_usecases/get_all_crop_varieties_by_crop_id_to_select_usecases/get_all_crop_varieties_by_crop_id_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/crop_variety_usecases/get_all_crop_varieties_by_crop_id_to_select_usecases/get_all_crop_varieties_by_crop_id_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/crop_variety_usecases/get_all_crop_varieties_by_crop_id_usecases/get_all_crop_varieties_by_crop_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/crop_variety_usecases/get_all_crop_varieties_by_crop_id_usecases/get_all_crop_varieties_by_crop_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/crop_variety_usecases/get_all_crop_variety_to_select_usecases/get_all_crop_varieties_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/crop_variety_usecases/get_all_crop_variety_to_select_usecases/get_all_crop_varieties_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/crop_variety_usecases/get_all_crop_variety_usecases/get_all_crop_varieties_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/crop_variety_usecases/get_all_crop_variety_usecases/get_all_crop_varieties_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/crop_variety_usecases/get_crop_variety_by_id_usecases/get_crop_variety_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/crop_variety_usecases/get_crop_variety_by_id_usecases/get_crop_variety_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/get_all_crops_to_select_usecases/get_all_crops_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/get_all_crops_to_select_usecases/get_all_crops_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/get_all_crops_usecases/get_all_crops_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/get_all_crops_usecases/get_all_crops_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/get_crop_by_id_usecases/get_crop_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/get_crop_by_id_usecases/get_crop_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_all_emploees_to_select_usecases/get_all_emploees_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_all_emploees_to_select_usecases/get_all_emploees_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_all_employees_by_farm_id_to_select_usecases/get_all_employees_by_farm_id_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_all_employees_by_farm_id_to_select_usecases/get_all_employees_by_farm_id_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_all_employees_by_farm_id_usecases/get_all_employees_by_farm_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_all_employees_by_farm_id_usecases/get_all_employees_by_farm_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_all_employees_usecases/get_all_employees_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_all_employees_usecases/get_all_employees_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_employee_by_id_usecase/get_employee_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_employee_by_id_usecase/get_employee_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/farm_plot_usecases/get_all_farm_plots_to_select_usecases/get_all_farm_plots_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/farm_plot_usecases/get_all_farm_plots_to_select_usecases/get_all_farm_plots_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/farm_plot_usecases/get_all_farm_plots_usecases/get_all_farm_plots_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/farm_plot_usecases/get_all_farm_plots_usecases/get_all_farm_plots_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/farm_plot_usecases/get_farm_plot_by_id_usecases/get_farm_plot_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/farm_plot_usecases/get_farm_plot_by_id_usecases/get_farm_plot_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/get_all_farms_by_cost_center_id_to_select_usecases/get_all_farms_by_cost_center_id_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/get_all_farms_by_cost_center_id_to_select_usecases/get_all_farms_by_cost_center_id_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/get_all_farms_by_cost_center_id_usecases/get_all_farms_by_cost_center_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/get_all_farms_by_cost_center_id_usecases/get_all_farms_by_cost_center_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/get_all_farms_to_select_usecases/get_all_farms_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/get_all_farms_to_select_usecases/get_all_farms_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/get_all_farms_usecases/get_all_farms_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/get_all_farms_usecases/get_all_farms_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/get_farm_by_id_usecases/get_farm_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/get_farm_by_id_usecases/get_farm_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/machinery_implement_usecases/get_all_machinery_implement_usecases/get_all_machinery_implements_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/machinery_implement_usecases/get_all_machinery_implement_usecases/get_all_machinery_implements_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/machinery_implement_usecases/get_all_machinery_implements_to_select_usecases/get_all_machinery_implements_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/machinery_implement_usecases/get_all_machinery_implements_to_select_usecases/get_all_machinery_implements_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/machinery_implement_usecases/get_machinery_implement_by_id/get_machinery_implement_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/machinery_implement_usecases/get_machinery_implement_by_id/get_machinery_implement_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/payment_method_usecases/get_all_payment_methods_to_select_usecase/get_all_payment_methods_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/payment_method_usecases/get_all_payment_methods_to_select_usecase/get_all_payment_methods_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/pest_usecases/get_all_pests_to_select_usecases/get_all_pests_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/pest_usecases/get_all_pests_to_select_usecases/get_all_pests_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/pest_usecases/get_all_pests_usecases/get_all_pests_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/pest_usecases/get_all_pests_usecases/get_all_pests_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/pest_usecases/get_pest_by_id_usecases/get_pest_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/pest_usecases/get_pest_by_id_usecases/get_pest_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/plots_usecases/get_all_plots_by_farm_id_usecases/get_all_plots_by_farm_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/plots_usecases/get_all_plots_by_farm_id_usecases/get_all_plots_by_farm_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/plots_usecases/get_all_plots_to_select_usecases/get_all_plots_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/plots_usecases/get_all_plots_to_select_usecases/get_all_plots_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/plots_usecases/get_all_plots_usecases/get_all_plots_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/plots_usecases/get_all_plots_usecases/get_all_plots_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/get_all_products_by_type_id_to_select_usecases/get_all_products_by_type_id_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/get_all_products_by_type_id_to_select_usecases/get_all_products_by_type_id_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/get_all_products_by_type_id_usecases/get_all_products_by_type_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/get_all_products_by_type_id_usecases/get_all_products_by_type_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/get_all_products_to_select_usecase/get_all_products_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/get_all_products_to_select_usecase/get_all_products_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/get_all_products_usecase/get_all_products_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/get_all_products_usecase/get_all_products_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/get_product_by_id_usecases/get_product_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/product_types_usecases/get_all_product_types_to_select_usecases/get_all_product_types_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/product_types_usecases/get_all_product_types_to_select_usecases/get_all_product_types_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/product_types_usecases/get_all_product_types_usecases/get_all_product_types_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/product_types_usecases/get_all_product_types_usecases/get_all_product_types_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/product_types_usecases/get_product_type_by_id_usecases/get_product_type_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/product_types_usecases/get_product_type_by_id_usecases/get_product_type_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/approve_purchase_request_by_id_usecases/approve_purchase_request_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/approve_purchase_request_by_id_usecases/approve_purchase_request_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/cancel_purchase_request_by_id_usecases/cancel_purchase_request_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/cancel_purchase_request_by_id_usecases/cancel_purchase_request_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/create_purchase_request_usecases/create_purchase_request_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/create_purchase_request_usecases/create_purchase_request_usecases_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/get_all_purchase_request_usecases/get_all_purchase_request_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/get_all_purchase_request_usecases/get_all_purchase_request_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/get_purchase_request_by_id_usecases/get_purchase_request_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/get_purchase_request_by_id_usecases/get_purchase_request_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/get_purchase_request_by_status_id_usecases/get_purchase_request_by_status_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/get_purchase_request_by_status_id_usecases/get_purchase_request_by_status_id_usecases_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/purchase_request_delivery_location_usecases/get_all_purchase_request_delivery_locations_to_select_usecases/get_all_purchase_request_delivery_locations_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/purchase_request_delivery_location_usecases/get_all_purchase_request_delivery_locations_to_select_usecases/get_all_purchase_request_delivery_locations_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/purchase_request_delivery_location_usecases/get_all_purchase_request_delivery_locations_usecases/get_all_purchase_request_delivery_locations_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/purchase_request_delivery_location_usecases/get_all_purchase_request_delivery_locations_usecases/get_all_purchase_request_delivery_locations_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/purchase_request_delivery_location_usecases/get_purchase_request_delivery_location_by_id_usecases/get_purchase_request_delivery_location_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/purchase_request_delivery_location_usecases/get_purchase_request_delivery_location_by_id_usecases/get_purchase_request_delivery_location_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/purchase_request_type_usecases/get_all_purchase_request_type_to_select_usecases/get_all_purchase_request_types_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/purchase_request_type_usecases/get_all_purchase_request_type_to_select_usecases/get_all_purchase_request_types_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/purchase_request_type_usecases/get_all_purchase_request_types_usecases/get_all_purchase_request_types_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/purchase_request_type_usecases/get_all_purchase_request_types_usecases/get_all_purchase_request_types_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/purchase_request_type_usecases/get_purchase_request_type_by_id_usecases/get_purchase_request_type_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/purchase_request_type_usecases/get_purchase_request_type_by_id_usecases/get_purchase_request_type_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/approve_service_order_by_id_usecase/approve_service_order_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/approve_service_order_by_id_usecase/approve_service_order_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/cancel_service_order_by_id_usecase/cancel_service_order_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/cancel_service_order_by_id_usecase/cancel_service_order_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/create_service_order_usecases/create_service_order_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/create_service_order_usecases/create_service_order_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/get_all_service_order_by_status_id_usecase/get_all_service_order_by_status_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/get_all_service_order_by_status_id_usecase/get_all_service_order_by_status_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/get_all_service_orders_to_select_usecases/get_all_service_orders_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/get_all_service_orders_to_select_usecases/get_all_service_orders_to_select_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/get_all_service_orders_usecases/get_all_service_orders_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/get_all_service_orders_usecases/get_all_service_orders_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/get_service_order_by_id_usecases/get_service_order_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/get_service_order_by_id_usecases/get_service_order_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/user_usecases/get_all_users_to_select_usecases/get_all_users_to_select_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/user_usecases/get_all_users_usecases/get_all_users_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/user_usecases/get_all_users_usecases/get_all_users_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/user_usecases/get_user_by_id_usecase/get_user_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/user_usecases/get_user_by_id_usecase/get_user_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/user_usecases/update_user_by_id_usecase/update_user_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/user_usecases/update_user_by_id_usecase/update_user_by_id_usecase_impl.dart';

import '../features/domain/usecases/agricultural_activity_usecases/agricultural_activity_type_usecases/get_all_agricultural_activity_types_usecases/get_all_agricultural_activity_types_usecase.dart';
import '../features/domain/usecases/agricultural_activity_usecases/agricultural_sub_activitiy_usecases/get_all_agricultural_sub_activities_to_select_usecases/get_all_agricultural_sub_activities_to_select_usecase.dart';
import '../features/domain/usecases/agricultural_activity_usecases/get_all_agricultural_activity_by_type_id_to_select_usecases/get_all_agricultural_activity_by_type_id_to_select_usecase_impl.dart';
import '../features/domain/usecases/product_usecases/get_product_by_id_usecases/get_product_by_id_usecase_impl.dart';

class UsecaseBinds {
  void binds(Injector i) {

    ///Agricultural Activity Type
    i.addLazySingleton<GetAgriculturalActivityTypeByIdUsecase>(GetAgriculturalActivityTypeByIdUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalActivityTypesToSelectUsecase>(GetAllAgriculturalActivityTypesToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalActivityTypesUsecase>(GetAllAgriculturalActivityTypesUsecaseImpl.new);

    ///Agricultural Sub Activity
    i.addLazySingleton<GetAgriculturalSubActivityByIdUsecase>(GetAgriculturalSubActivityByIdUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalSubActivitiesByActivityIdToSelectUsecase>(GetAllAgriculturalSubActivitiesByActivityIdToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalSubActivitiesToSelectUsecase>(GetAllAgriculturalSubActivitiesByActivityIdToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalSubActivitiesUsecase>(GetAllAgriculturalSubActivitiesUsecaseImpl.new);

    ///Agricultural Activity
    i.addLazySingleton<GetAllAgriculturalActivityByTypeIdUsecase>(GetAllAgriculturalActivityByTypeIdUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalActivitiesToSelectUsecase>(GetAllAgriculturalActivitiesToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalActivitiesUsecase>(GetAllAgriculturalSubActivitiesUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalActivitiesByTypeIdToSelectUsecase>(GetAllAgriculturalActivitiesByTypeIdToSelectUsecaseImpl.new);

    ///Agricultural Input Class
    i.addLazySingleton<GetAgriculturalInputClassByIdUsecase>(GetAgriculturalInputClassByIdUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalInputClassesUsecase>(GetAllAgriculturalInputClassesUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalInputClassesToSelectUsecase>(GetAllAgriculturalInputClassesToSelectUsecaseImpl.new);

    ///Agricultural Input
    i.addLazySingleton<GetAgriculturalInputByIdUsecase>(GetAgriculturalInputByIdUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalInputsByClassIdToSelectUsecase>(GetAllAgriculturalInputsByClassIdToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalInputsByClassIdUsecase>(GetAllAgriculturalInputsByClassIdUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalInputsToSelectUsecase>(GetAllAgriculturalInputsToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllAgriculturalInputsUsecase>(GetAllAgriculturalInputsUsecaseImpl.new);

    ///Authentication
    i.addLazySingleton<AuthenticateUsecase>(AuthenticateUsecaseImpl.new);
    i.addLazySingleton<RecoverPasswordUsecase>(RecoverPasswordUsecaseImpl.new);
    i.addLazySingleton<UpdatePasswordUsecase>(UpdatePasswordUsecaseImpl.new);

    ///Company Segment
    i.addLazySingleton<GetAllCompanySegmentsToSelectUsecase>(GetAllCompanySegmentsToSelectUsecaseImpl.new);
    i.addLazySingleton<GetCompanySegmentByIdUsecase>(GetCompanySegmentByIdUsecaseImpl.new);
    i.addLazySingleton<GetAllCompanySegmentsUsecase>(GetAllCompanySegmentsUsecaseImpl.new);

    ///Company
    i.addLazySingleton<GetAllCompaniesUsecase>(GetAllCompaniesUsecaseImpl.new);
    i.addLazySingleton<GetAllCompaniesToSelectUsecase>(GetAllCompaniesToSelectUsecaseImpl.new);
    i.addLazySingleton<GetCompanyByIdUsecase>(GetCompanyByIdUsecaseImpl.new);

    ///Contract
    i.addLazySingleton<GetAllContractsToSelectUsecase>(GetAllContractsToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllContractsUsecase>(GetAllContractsUsecaseImpl.new);
    i.addLazySingleton<GetContractByIdUsecase>(GetContractByIdUsecaseImpl.new);

    ///Cost Center
    i.addLazySingleton<GetAllCostCentersByCostCenterTypeIdToSelectUsecase>(GetAllCostCentersByCostCenterTypeIdToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllCostCentersByCostCenterTypeIdUsecase>(GetAllCostCentersByCostCenterTypeIdUsecaseImpl.new);
    i.addLazySingleton<GetAllCostCentersToSelectUsecase>(GetAllCostCentersByCostCenterTypeIdToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllCostCentersUsecase>(GetAllCostCentersUsecaseImpl.new);
    i.addLazySingleton<GetCostCenterByIdUsecase>(GetCostCenterByIdUsecaseImpl.new);

    ///Crop Variety
    i.addLazySingleton<GetAllCropVarietiesByCropIdToSelectUsecase>(GetAllCropVarietiesByCropIdToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllCropVarietiesByCropIdUsecase>(GetAllCropVarietiesByCropIdUsecaseImpl.new);
    i.addLazySingleton<GetAllCropVarietiesToSelectUsecase>(GetAllCropVarietiesToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllCropVarietiesUsecase>(GetAllCropVarietiesUsecaseImpl.new);
    i.addLazySingleton<GetCropVarietyByIdUsecase>(GetCropVarietyByIdUsecaseImpl.new);

    ///Crop
    i.addLazySingleton<GetAllCropsToSelectUsecase>(GetAllCropsToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllCropsUsecase>(GetAllCropsUsecaseImpl.new);
    i.addLazySingleton<GetCropByIdUsecase>(GetCropByIdUsecaseImpl.new);

    ///Employee
    i.addLazySingleton<GetAllEmployeesToSelectUsecase>(GetAllEmployeesToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllEmployeesByFarmIdToSelectUsecase>(GetAllEmployeesByFarmIdToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllEmployeesByFarmIdUsecase>(GetAllEmployeesByFarmIdUsecaseImpl.new);
    i.addLazySingleton<GetAllEmployeesUsecase>(GetAllEmployeesUsecaseImpl.new);
    i.addLazySingleton<GetEmployeeByIdUsecase>(GetEmployeeByIdUsecaseImpl.new);

    //Farm Plot
    i.addLazySingleton<GetAllFarmPlotsToSelectUsecase>(GetAllFarmPlotsToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllFarmPlotsUsecase>(GetAllFarmPlotsUsecaseImpl.new);
    i.addLazySingleton<GetFarmPlotByIdUsecase>(GetFarmPlotByIdUsecaseImpl.new);

    ///Farm
    i.addLazySingleton<GetAllFarmsByCostCenterIdToSelectUsecase>(GetAllFarmsByCostCenterIdToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllFarmsByCostCenterIdUsecase>(GetAllFarmsByCostCenterIdUsecaseImpl.new);
    i.addLazySingleton<GetAllFarmsToSelectUsecase>(GetAllFarmsToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllFarmsUsecase>(GetAllFarmsUsecaseImpl.new);
    i.addLazySingleton<GetFarmByIdUsecase>(GetFarmByIdUsecaseImpl.new);

    ///Machinery Implement
    i.addLazySingleton<GetAllMachineryImplementsUsecase>(GetAllMachineryImplementsUsecaseImpl.new);
    i.addLazySingleton<GetAllMachineryImplementsToSelectUsecase>(GetAllMachineryImplementsToSelectUsecaseImpl.new);
    i.addLazySingleton<GetMachineryImplementByIdUsecase>(GetMachineryImplementByIdUsecaseImpl.new);

    ///Payment Method
    i.addLazySingleton<GetAllPaymentMethodsToSelectUsecase>(GetAllPaymentMethodsToSelectUsecaseImpl.new);

    ///Pest
    i.addLazySingleton<GetAllPestsToSelectUsecase>(GetAllPestsToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllPestsUsecase>(GetAllPestsUsecaseImpl.new);
    i.addLazySingleton<GetPestByIdUsecase>(GetPestByIdUsecaseImpl.new);

    ///Plots
    i.addLazySingleton<GetAllPlotsByFarmIdUsecase>(GetAllPlotsByFarmIdUsecaseImpl.new);
    i.addLazySingleton<GetAllPlotsToSelectUsecase>(GetAllPlotsToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllPlotsUsecase>(GetAllPlotsUsecaseImpl.new);

    ///Product
    i.addLazySingleton<GetAllProductsByTypeIdToSelectUsecase>(GetAllProductsByTypeIdToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllProductsByTypeIdUsecase>(GetAllProductsByTypeIdUsecaseImpl.new);
    i.addLazySingleton<GetAllProductsToSelectUsecase>(GetAllProductsToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllProductsUsecase>(GetAllProductsUsecaseImpl.new);
    i.addLazySingleton<GetProductByIdUsecase>(GetProductByIdUsecaseImpl.new);

    ///Product type
    i.addLazySingleton<GetAllProductTypesToSelectUsecase>(GetAllProductTypesToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllProductTypesUsecase>(GetAllProductTypesUsecaseImpl.new);
    i.addLazySingleton<GetProductTypeByIdUsecase>(GetProductTypeByIdUsecaseImpl.new);

    ///Purchase request
    i.addLazySingleton<ApprovePurchaseRequestByIdUsecase>(ApprovePurchaseRequestByIdUsecaseImpl.new);
    i.addLazySingleton<CancelPurchaseRequestByIdUsecase>(CancelPurchaseRequestByIdUsecaseImpl.new);
    i.addLazySingleton<CreatePurchaseRequestUsecase>(CreatePurchaseRequestUsecaseImpl.new);
    i.addLazySingleton<GetAllPurchaseRequestUsecase>(GetAllPurchaseRequestUsecaseImpl.new);
    i.addLazySingleton<GetPurchaseRequestByStatusIdUsecase>(GetPurchaseRequestByStatusIdUsecaseImpl.new);
    i.addLazySingleton<GetPurchaseRequestByIdUsecase>(GetPurchaseRequestByIdUsecaseImpl.new);

    ///Purchase Request Delivery Location
    i.addLazySingleton<GetAllPurchaseRequestDeliveryLocationsToSelectUsecase>(GetAllPurchaseRequestDeliveryLocationsToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllPurchaseRequestDeliveryLocationsUsecase>(GetAllPurchaseRequestDeliveryLocationsUsecaseImpl.new);
    i.addLazySingleton<GetPurchaseRequestDeliveryLocationByIdUsecase>(GetPurchaseRequestDeliveryLocationByIdUsecaseImpl.new);

    ///Purchase Request Type
    i.addLazySingleton<GetAllPurchaseRequestTypesToSelectUsecase>(GetAllPurchaseRequestTypesToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllPurchaseRequestTypesUsecase>(GetAllPurchaseRequestTypesUsecaseImpl.new);
    i.addLazySingleton<GetPurchaseRequestTypeByIdUsecase>(GetPurchaseRequestTypeByIdUsecaseImpl.new);

    ///Service Order
    i.addLazySingleton<ApproveServiceOrderByIdUsecase>(ApproveServiceOrderByIdUsecaseImpl.new);
    i.addLazySingleton<CancelServiceOrderByIdUsecase>(CancelServiceOrderByIdUsecaseImpl.new);
    i.addLazySingleton<CreateServiceOrderUsecase>(CreateServiceOrderUsecaseImpl.new);
    i.addLazySingleton<GetAllServiceOrderByStatusIdUsecase>(GetAllServiceOrderByStatusIdUsecaseImpl.new);
    i.addLazySingleton<GetAllServiceOrdersToSelectUsecase>(GetAllServiceOrdersToSelectUsecaseImpl.new);
    i.addLazySingleton<GetAllServiceOrdersUsecase>(GetAllServiceOrdersUsecaseImpl.new);
    i.addLazySingleton<GetServiceOrderByIdUsecase>(GetServiceOrderByIdUsecaseImpl.new);

    ///User
    i.addLazySingleton<GetAllUsersToSelectUsecase>(GetServiceOrderByIdUsecaseImpl.new);
    i.addLazySingleton<GetAllUsersUsecase>(GetAllUsersUsecaseImpl.new);
    i.addLazySingleton<GetUserByIdUsecase>(GetUserByIdUsecaseImpl.new);
    i.addLazySingleton<UpdateUserByIdUsecase>(UpdateUserByIdUsecaseImpl.new);




  }
}