import 'package:dio/dio.dart';
import 'package:flutter_modular/flutter_modular.dart';
import 'package:new_ezagro_flutter/consts/app_routes.dart';
import 'package:new_ezagro_flutter/core/connection_manager/connection_status.dart';
import 'package:new_ezagro_flutter/core/connection_manager/connection_status_impl.dart';
import 'package:new_ezagro_flutter/core/local_storage/local_storage_client.dart';
import 'package:new_ezagro_flutter/core/local_storage/local_storage_client_shared_prefs_impl.dart';
import 'package:new_ezagro_flutter/design_system/strings/app_strings_portuguese.dart';
import 'package:new_ezagro_flutter/features/data/datasources/remote_datasource/authentication_datasource/authentication_datasource.dart';
import 'package:new_ezagro_flutter/features/data/datasources/remote_datasource/authentication_datasource/authentication_datasources_impl.dart';
import 'package:new_ezagro_flutter/features/data/datasources/remote_datasource/company_datasources/company_datasource.dart';
import 'package:new_ezagro_flutter/features/data/datasources/remote_datasource/company_datasources/company_datasource_impl.dart';
import 'package:new_ezagro_flutter/features/data/datasources/remote_datasource/user_datasources/user_datasource.dart';
import 'package:new_ezagro_flutter/features/data/datasources/remote_datasource/user_datasources/user_datasource_impl.dart';
import 'package:new_ezagro_flutter/features/data/repositories/authentication_repository/authentication_repository_impl.dart';
import 'package:new_ezagro_flutter/features/data/repositories/company_repositories/company_repository_impl.dart';
import 'package:new_ezagro_flutter/features/data/repositories/contract_repositories/contract_repository_impl.dart';
import 'package:new_ezagro_flutter/features/data/repositories/pest_repositories/pest_repository_impl.dart';
import 'package:new_ezagro_flutter/features/data/repositories/user_repositories/user_repository_impl.dart';
import 'package:new_ezagro_flutter/features/domain/repositories/authentication_repository/authentication_repository.dart';
import 'package:new_ezagro_flutter/features/domain/repositories/company_repositories/company_repository.dart';
import 'package:new_ezagro_flutter/features/domain/repositories/contract_repositories/contract_repository.dart';
import 'package:new_ezagro_flutter/features/domain/repositories/pest_repositories/pest_repository.dart';
import 'package:new_ezagro_flutter/features/domain/repositories/purchase_request_repositories/purchase_request_repository.dart';
import 'package:new_ezagro_flutter/features/domain/repositories/user_repositories/user_repository.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/activity_usecase/activity_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/activity_usecase/activity_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/authentication_usecases/authenticate_usecase/authenticate_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/authentication_usecases/recover_password_usecase/recover_password_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/authentication_usecases/recover_password_usecase/recover_password_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/authentication_usecases/update_password/update_password_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/get_all_companies_usecase/get_all_companies_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/get_all_companies_usecase/get_all_companies_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/get_company_by_id_usecase/get_company_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/company_usecases/get_company_by_id_usecase/get_company_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/contract_usecases/get_contract_by_id_usecase/get_contract_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/contract_usecases/get_contract_by_id_usecase/get_contract_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/contract_usecases/get_contract_list_usecase/get_contract_list_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/contract_usecases/get_contract_list_usecase/get_contract_list_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/cost_center_usecases/cost_center_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/cost_center_usecases/cost_center_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/crop_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/crop_usecases/crop_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_employee_by_id_usecase/get_employee_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_employee_by_id_usecase/get_employee_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_employee_list_usecase/get_employee_list_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/employee_usecase/get_employee_list_usecase/get_employee_list_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/executor_usecases/executor_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/executor_usecases/executor_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/cost_center_farm_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/cost_center_farm_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/farm_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/farm_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/get_farm_by_id_usecase/get_farm_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/farm_usecases/get_farm_list_usecase/get_farm_list_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/machinery_usecases/get_machinery_implement_by_id/get_machinery_implement_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/machinery_usecases/machinery_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/machinery_usecases/machinery_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/pest_usecases/pest_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/pest_usecases/pest_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/plots_usecases/plots_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/plots_usecases/plots_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/plots_usecases/plots_with_farm_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/plots_usecases/plots_with_farm_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/product_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/product_usecases/product_usecases_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/purchase_request_usecases/get_all_purchase_request_usecases/get_all_purchase_request_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/approve_service_order_by_id_usecase/approve_service_order_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/approve_service_order_by_id_usecase/approve_service_order_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/cancel_service_order_by_id_usecase/cancel_service_order_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/create_service_order_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/create_service_order_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/get_service_order_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/service_order_usecase/get_service_order_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/user_usecases/get_all_users_usecases/get_all_users_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/user_usecases/get_all_users_usecases/get_all_users_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/user_usecases/get_user_by_id_usecase/get_user_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/user_usecases/get_user_by_id_usecase/get_user_by_id_usecase_impl.dart';
import 'package:new_ezagro_flutter/features/domain/usecases/user_usecases/update_user_by_id_usecase/update_user_by_id_usecase.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/authentication_module/recover_password_pages/recover_password_success_page.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/authentication_module/recover_password_pages/repeat_password_page.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/authentication_module/recover_password_pages/temp_password_page.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/authentication_module/recover_password_pages/username_input_page.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/home/home_controller.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/home/home_page.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/home/home_screen.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/register/company/controller/company_controller.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/register/contracts/contract_list_page.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/register/contracts/controller/contract_controller.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/register/employees/controller/employee_controller.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/register/employees/employees_list_page.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/register/farm/controller/farm_controller.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/register/farm/farm_list_page.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/register/machinery/machinery_list_page.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/service_order/controller/plots_list_controller/plots_list_controller.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/service_order/controller/service_order_list_controller/service_order_list_controller.dart';
import 'package:new_ezagro_flutter/features/presenter/modules/service_order/service_order_page/plots_list_page.dart';
import 'core/http_client/http_client.dart';
import 'core/http_client/http_client_dio_imp.dart';
import 'core/local_storage/local_storage_client_secure_impl.dart';
import 'features/data/datasources/remote_datasource/employee_datasources/employee_datasource.dart';
import 'features/data/datasources/remote_datasource/employee_datasources/employee_datasource_impl.dart';
import 'features/data/datasources/remote_datasource/contract_datasources/contract_datasource.dart';
import 'features/data/datasources/remote_datasource/contract_datasources/contract_datasource_impl.dart';
import 'features/data/datasources/remote_datasource/product_datasources/Product_datasource.dart';
import 'features/data/datasources/remote_datasource/activity_datasources/activity_datasource.dart';
import 'features/data/datasources/remote_datasource/activity_datasources/activity_datasource_impl.dart';
import 'features/data/datasources/remote_datasource/cost_center_datasource/cost_center_datasource.dart';
import 'features/data/datasources/remote_datasource/cost_center_datasource/cost_center_datasource_impl.dart';
import 'features/data/datasources/remote_datasource/crop_datasource/crop_datasource.dart';
import 'features/data/datasources/remote_datasource/crop_datasource/crop_datasource_impl.dart';
import 'features/data/datasources/remote_datasource/executors_datasources/executors_datasource.dart';
import 'features/data/datasources/remote_datasource/executors_datasources/executors_datasource_impl.dart';
import 'features/data/datasources/remote_datasource/farm_datasource/farm_datasource.dart';
import 'features/data/datasources/remote_datasource/farm_datasource/farm_datasource_impl.dart';
import 'features/data/datasources/remote_datasource/machinery_datasources/machinery_datasource.dart';
import 'features/data/datasources/remote_datasource/machinery_datasources/machinery_datasource_impl.dart';
import 'features/data/datasources/remote_datasource/pest_datasources/pest_datasource.dart';
import 'features/data/datasources/remote_datasource/pest_datasources/pest_datasource_impl.dart';
import 'features/data/datasources/remote_datasource/plots_datasource/plots_datasource.dart';
import 'features/data/datasources/remote_datasource/plots_datasource/plots_datasource_impl.dart';
import 'features/data/datasources/remote_datasource/product_datasources/product_datasource_impl.dart';
import 'features/data/datasources/remote_datasource/purchase_request_datasources/purchase_request_datasource.dart';
import 'features/data/datasources/remote_datasource/purchase_request_datasources/purchase_request_datasource_impl.dart';
import 'features/data/datasources/remote_datasource/service_order_datasources/service_order_datasource.dart';
import 'features/data/datasources/remote_datasource/service_order_datasources/service_order_datasource_impl.dart';
import 'features/data/repositories/activity_repositories/activity_repository_impl.dart';
import 'features/data/repositories/cost_center_repositories/cost_center_repository_impl.dart';
import 'features/data/repositories/crop_repositories/crop_repository_impl.dart';
import 'features/data/repositories/employee_repositories/employee_repository_impl.dart';
import 'features/data/repositories/executors_repositories/executors_repository_impl.dart';
import 'features/data/repositories/farm_repositories/farm_repository_impl.dart';
import 'features/data/repositories/machinery_repositories/machinery_repository_impl.dart';
import 'features/data/repositories/plots_repositories/plots_repository_impl.dart';
import 'features/data/repositories/products_repositories/products_repository_impl.dart';
import 'features/data/repositories/purchase_request_repositories/purchase_request_repository_impl.dart';
import 'features/data/repositories/service_order_repositories/service_order_repository_impl.dart';
import 'features/domain/repositories/activity_repository/activity_repository.dart';
import 'features/domain/repositories/cost_center_repositories/cost_center_repository.dart';
import 'features/domain/repositories/crop_repositories/crop_repository.dart';
import 'features/domain/repositories/employee_repositories/employee_repository.dart';
import 'features/domain/repositories/executors_repositories/executors_repository.dart';
import 'features/domain/repositories/farm_repositories/farm_repository.dart';
import 'features/domain/repositories/machinery_repositories/machinery_repository.dart';
import 'features/domain/repositories/plots_repositories/plots_repository.dart';
import 'features/domain/repositories/product_repositories/product_repository.dart';
import 'features/domain/repositories/service_order_repositories/service_order_repository.dart';
import 'features/domain/usecases/authentication_usecases/authenticate_usecase/authenticate_usecase.dart';
import 'features/domain/usecases/authentication_usecases/update_password/update_password_usecase_impl.dart';
import 'features/domain/usecases/employee_usecase/employee_usecase.dart';
import 'features/domain/usecases/employee_usecase/employee_usecase_impl.dart';
import 'features/domain/usecases/farm_usecases/get_farm_by_id_usecase/get_farm_by_id_usecase_impl.dart';
import 'features/domain/usecases/farm_usecases/get_farm_list_usecase/get_farm_list_usecase.dart';
import 'features/domain/usecases/machinery_usecases/get_all_machinery_usecases/get_all_machinery_usecase.dart';
import 'features/domain/usecases/machinery_usecases/get_all_machinery_usecases/get_all_machinery_usecase_impl.dart';
import 'features/domain/usecases/machinery_usecases/get_machinery_implement_by_id/get_machinery_implement_by_id_usecase_impl.dart';
import 'features/domain/usecases/purchase_request_usecases/approve_purchase_request_by_id_usecases/approve_purchase_request_by_id_usecase.dart';
import 'features/domain/usecases/purchase_request_usecases/approve_purchase_request_by_id_usecases/approve_purchase_request_by_id_usecase_impl.dart';
import 'features/domain/usecases/purchase_request_usecases/cancel_purchase_request_by_id_usecases/cancel_purchase_request_by_id_usecase.dart';
import 'features/domain/usecases/purchase_request_usecases/cancel_purchase_request_by_id_usecases/cancel_purchase_request_by_id_usecase_impl.dart';
import 'features/domain/usecases/purchase_request_usecases/get_all_purchase_request_usecases/get_all_purchase_request_usecase_impl.dart';
import 'features/domain/usecases/purchase_request_usecases/get_purchase_request_by_id_usecases/get_purchase_request_by_id_usecase.dart';
import 'features/domain/usecases/purchase_request_usecases/get_purchase_request_by_id_usecases/get_purchase_request_by_id_usecase_impl.dart';
import 'features/domain/usecases/purchase_request_usecases/get_purchase_request_by_status_id_usecases/get_purchase_request_by_status_id_usecase.dart';
import 'features/domain/usecases/purchase_request_usecases/get_purchase_request_by_status_id_usecases/get_purchase_request_by_status_id_usecases_impl.dart';
import 'features/domain/usecases/service_order_usecase/cancel_service_order_by_id_usecase/cancel_service_order_by_id_usecase_impl.dart';
import 'features/domain/usecases/service_order_usecase/get_service_order_by_status_id_usecase/get_service_order_by_status_id_usecase.dart';
import 'features/domain/usecases/service_order_usecase/get_service_order_by_status_id_usecase/get_service_order_by_status_id_usecase_impl.dart';
import 'features/domain/usecases/service_order_usecase/service_order_list_usecase.dart';
import 'features/domain/usecases/service_order_usecase/service_order_list_usecase_impl.dart';
import 'features/domain/usecases/user_usecases/update_user_by_id_usecase/update_user_by_id_usecase_impl.dart';
import 'features/presenter/modules/approvals_module/approvals_detail/approvals_detail_controller.dart';
import 'features/presenter/modules/approvals_module/approvals_detail/approvals_purchase_request_detail_page.dart';
import 'features/presenter/modules/approvals_module/approvals_detail/approvals_service_order_detail_page.dart';
import 'features/presenter/modules/approvals_module/approvals_list/approvals_list_controller.dart';
import 'features/presenter/modules/approvals_module/approvals_list/approvals_list_page.dart';
import 'features/presenter/modules/authentication_module/authentication_controller/authentication_controller.dart';
import 'features/presenter/modules/authentication_module/login_pages/login_page.dart';
import 'features/presenter/modules/authentication_module/recover_password_pages/new_password_page.dart';
import 'features/presenter/modules/authentication_module/register_page/register_fifth_step_page.dart';
import 'features/presenter/modules/authentication_module/register_page/register_first_step_page.dart';
import 'features/presenter/modules/authentication_module/register_page/register_fourth_step_page.dart';
import 'features/presenter/modules/authentication_module/register_page/register_second_step_page.dart';
import 'features/presenter/modules/authentication_module/register_page/register_third_step_page.dart';
import 'features/presenter/modules/documents/documents_page/documents_page.dart';
import 'features/presenter/modules/purchase_request/purchase_request_controllers/purchase_request_list_controller.dart';
import 'features/presenter/modules/purchase_request/purchase_request_list_page.dart';
import 'features/presenter/modules/register/company/company_list_page.dart';
import 'features/presenter/modules/register/company/company_page.dart';
import 'features/presenter/modules/register/contracts/contract_page.dart';
import 'features/presenter/modules/register/employees/employee_page.dart';
import 'features/presenter/modules/register/farm/farm_page.dart';
import 'features/presenter/modules/register/machinery/machinery_controller.dart';
import 'features/presenter/modules/register/machinery/machinery_implements_page.dart';
import 'features/presenter/modules/register/registers_page.dart';
import 'features/presenter/modules/service_order/controller/create_service_order_controller/create_service_order_controller.dart';
import 'features/presenter/modules/service_order/controller/service_order_controller/service_order_controller.dart';
import 'features/presenter/modules/service_order/create_service_order_page/create_service_order_page.dart';
import 'features/presenter/modules/service_order/service_order_list_page/service_order_list_page.dart';
import 'features/presenter/modules/service_order/service_order_page/service_order_page.dart';
import 'features/presenter/modules/splash/splash_page/splash_page.dart';

class AppModule extends Module {

  @override
  void binds(Injector i) {

    //Core Binds
    i.addLazySingleton<LocalStorageClient>(LocalStorageClientSharedPrefsImpl.new,
        key: AppStringsPortuguese.storageTypeLocal);
    i.addLazySingleton<LocalStorageClient>(LocalStorageClientSecureImpl.new,
        key: AppStringsPortuguese.storageTypeSecure);
    i.addLazySingleton<LogInterceptor>(LogInterceptor.new);
    i.addSingleton<HttpClient>(HttpClientDioImp.new);
    i.addSingleton<ConnectionStatus>(ConnectionStatusImpl.new);

    //Usecase
    i.addLazySingleton<AuthenticateUsecase>(AuthenticateUsecaseImpl.new);
    i.addLazySingleton<RecoverPasswordUsecase>(RecoverPasswordUsecaseImpl.new);
    i.addLazySingleton<UpdatePasswordUsecase>(UpdatePasswordUsecaseImpl.new);
    i.addLazySingleton<ServiceOrderListUsecase>(ServiceOrderListUsecaseImpl.new);
    i.addLazySingleton<ActivityUsecase>(ActivityUsecaseImpl.new);
    i.addLazySingleton<CostCenterUsecase>(CostCenterUsecaseImpl.new);
    i.addLazySingleton<FarmUsecase>(FarmUsecaseImpl.new);
    i.addLazySingleton<CropUsecase>(CropUsecaseImpl.new);
    i.addLazySingleton<PlotsUsecase>(PlotsUsecaseImpl.new);
    i.addLazySingleton<ExecutorUsecase>(ExecutorUsecaseImpl.new);
    i.addLazySingleton<MachineryUsecase>(MachineryUsecaseImpl.new);
    i.addLazySingleton<ProductUsecase>(ProductUsecaseImpl.new);
    i.addLazySingleton<EmployeeUsecase>(EmployeeUsecaseImpl.new);
    i.addLazySingleton<CreateServiceOrderUsecase>(CreateServiceOrderUsecaseImpl.new);
    i.addLazySingleton<GetServiceOrderByIdUsecase>(GetServiceOrderByIdUsecaseImpl.new);
    i.addLazySingleton<GetServiceOrderByStatusIdUsecase>(GetServiceOrderByStatusIdUsecaseImpl.new);
    i.addLazySingleton<GetAllPurchaseRequestUsecase>(GetAllPurchaseRequestUsecaseImpl.new);
    i.addLazySingleton<GetPurchaseRequestByIdUsecase>(GetPurchaseRequestByIdUsecaseImpl.new);
    i.addLazySingleton<ApprovePurchaseRequestByIdUsecase>(ApprovePurchaseRequestByIdUsecaseImpl.new);
    i.addLazySingleton<CancelPurchaseRequestByIdUsecase>(CancelPurchaseRequestByIdUsecaseImpl.new);
    i.addLazySingleton<GetPurchaseRequestByStatusIdUsecase>(GetPurchaseRequestByStatusIdUsecaseImpl.new);
    i.addLazySingleton<ApproveServiceOrderByIdUsecase>(ApproveServiceOrderByIdUsecaseImpl.new);
    i.addLazySingleton<CancelServiceOrderByIdUsecase>(CancelServiceOrderByIdUsecaseImpl.new);

    i.addLazySingleton<PestUsecase>(PestUsecaseImpl.new);
    i.addLazySingleton<CostCenterFarmUsecase>(CostCenterFarmUsecaseImpl.new);
    i.addLazySingleton<PlotsWithFarmIdUsecase>(PlotsWithFarmIdUsecaseImpl.new);
    i.addLazySingleton<GetFarmByIdUsecase>(GetFarmByIdUsecaseImpl.new);

    i.addLazySingleton<GetAllUsersUsecase>(GetAllUsersUsecaseImpl.new);
    i.addLazySingleton<GetAllMachineryUsecase>(GetAllMachineryUsecaseImpl.new);
    i.addLazySingleton<GetMachineryImplementByIdUsecase>(GetMachineryImplementByIdUsecaseImpl.new);
    i.addLazySingleton<GetUserByIdUsecase>(GetUserByIdUsecaseImpl.new);
    i.addLazySingleton<UpdateUserByIdUsecase>(UpdateUserByIdUsecaseImpl.new);
    i.addLazySingleton<GetAllCompaniesUsecase>(GetAllCompaniesUsecaseImpl.new);
    i.addLazySingleton<GetCompanyByIdUsecase>(GetCompanyByIdUsecaseImpl.new);
    i.addLazySingleton<GetFarmListUsecase>(GetFarmListUsecaseImpl.new);
    i.addLazySingleton<GetEmployeeListUsecase>(GetEmployeeListUsecaseImpl.new);
    i.addLazySingleton<GetEmployeeByIdUsecase>(GetEmployeeByIdUsecaseImpl.new);
    i.addLazySingleton<GetContractListUsecase>(GetContractListUsecaseImpl.new);
    i.addLazySingleton<GetContractByIdUsecase>(GetContractByIdUsecaseImpl.new);

    //Repository
    i.addLazySingleton<AuthenticationRepository>(AuthenticationRepositoryImpl.new);
    i.addLazySingleton<ServiceOrderRepository>(ServiceOrderRepositoryImpl.new);
    i.addLazySingleton<ActivityRepository>(ActivityRepositoryImpl.new);
    i.addLazySingleton<CostCenterRepository>(CostCenterRepositoryImpl.new);
    i.addLazySingleton<FarmRepository>(FarmRepositoryImpl.new);
    i.addLazySingleton<CropRepository>(CropRepositoryImpl.new);
    i.addLazySingleton<PlotsRepository>(PlotsRepositoryImpl.new);
    i.addLazySingleton<ExecutorsRepository>(ExecutorsRepositoryImpl.new);
    i.addLazySingleton<MachineryRepository>(MachineryRepositoryImpl.new);
    i.addLazySingleton<ProductRepository>(ProductRepositoryImpl.new);
    i.addLazySingleton<EmployeeRepository>(EmployeeRepositoryImpl.new);
    i.addLazySingleton<PestRepository>(PestRepositoryImpl.new);
    i.addLazySingleton<UserRepository>(UserRepositoryImpl.new);
    i.addLazySingleton<CompanyRepository>(CompanyRepositoryImpl.new);
    i.addLazySingleton<ContractRepository>(ContractRepositoryImpl.new);
    i.addLazySingleton<PurchaseRequestRepository>(PurchaseRequestRepositoryImpl.new);

    //Datasource
    i.addLazySingleton<AuthenticationDatasource>(AuthenticationDatasourceImpl.new);
    i.addLazySingleton<ServiceOrderDatasource>(ServiceOrderDatasourceImpl.new);
    i.addLazySingleton<ActivityDatasource>(ActivityDatasourceImpl.new);
    i.addLazySingleton<CostCenterDatasource>(CostCenterDatasourceImpl.new);
    i.addLazySingleton<FarmDatasource>(FarmDatasourceImpl.new);
    i.addLazySingleton<CropDatasource>(CropDatasourceImpl.new);
    i.addLazySingleton<PlotsDatasource>(PlotsDatasourceImpl.new);
    i.addLazySingleton<ExecutorsDatasource>(ExecutorsDatasourceImpl.new);
    i.addLazySingleton<MachineryDatasource>(MachineryDatasourceImpl.new);
    i.addLazySingleton<ProductDatasource>(ProductDatasourceImpl.new);
    i.addLazySingleton<EmployeeDatasource>(EmployeeDatasourceImpl.new);
    i.addLazySingleton<PestDatasource>(PestDatasourceImpl.new);
    i.addLazySingleton<UserDatasource>(UserDatasourceImpl.new);
    i.addLazySingleton<CompanyDatasource>(CompanyDatasourceImpl.new);
    i.addLazySingleton<ContractDatasource>(ContractDatasourceImpl.new);
    i.addLazySingleton<PurchaseRequestDatasource>(PurchaseRequestDatasourceImpl.new);

    //Controllers
    i.addLazySingleton<AuthenticationController>(AuthenticationController.new);
    i.addLazySingleton<CreateServiceOrderController>(CreateServiceOrderController.new);
    i.addLazySingleton<ServiceOrderListController>(ServiceOrderListController.new);
    i.addLazySingleton<ServiceOrderController>(ServiceOrderController.new);
    i.addLazySingleton<PlotsListController>(PlotsListController.new);
    i.addLazySingleton<CompanyController>(CompanyController.new);
    i.addLazySingleton<FarmController>(FarmController.new);
    i.addLazySingleton<EmployeeController>(EmployeeController.new);
    i.addLazySingleton<ContractController>(ContractController.new);
    i.addLazySingleton<MachineryController>(MachineryController.new);
    i.addLazySingleton<ApprovalsListController>(ApprovalsListController.new);
    i.addLazySingleton<ApprovalsDetailController>(ApprovalsDetailController.new);
    i.addLazySingleton<HomeController>(HomeController.new);
    i.addLazySingleton<PurchaseRequestListController>(PurchaseRequestListController.new);
    super.binds(i);
  }

  @override
  void routes(RouteManager r) {
    r.child(AppRoutes.appDefaultPage, child: (context) => PurchaseRequestListPage ());
    r.child(AppRoutes.appSplashPage, child: (context) => const SplashPage());
    r.child(AppRoutes.appLoginPage, child: (context) => LoginPage());
    r.child(AppRoutes.appRegistersPage, child: (context) => RegistersPage());
    r.child(AppRoutes.appUsernameInputPage, child: (context) => UsernameInputPage());
    r.child(AppRoutes.appTempPasswordPage, child: (context) => TempPasswordPage());
    r.child(AppRoutes.appRepeatPasswordPage, child: (context) => RepeatPasswordPage());
    r.child(AppRoutes.appNewPasswordPage, child: (context) => NewPasswordPage());
    r.child(AppRoutes.appRecoverPasswordSuccessPage, child: (context) => RecoverPasswordSuccessPage());
    r.child(AppRoutes.appRegisterFirstStepPage, child: (context) => const RegisterFirstStepPage());
    r.child(AppRoutes.appRegisterSecondStepPage, child: (context) => const RegisterSecondStepPage());
    r.child(AppRoutes.appRegisterThirdStepPage, child: (context) => const RegisterThirdStepPage());
    r.child(AppRoutes.appRegisterFourthStepPage, child: (context) => const RegisterFourthStepPage());
    r.child(AppRoutes.appRegisterFifthStepPage, child: (context) => const RegisterFifthStepPage());
    r.child(AppRoutes.appDocumentsPage, child: (context) => const DocumentsPage());
    r.child(AppRoutes.appHomePage, child: (context) => const HomePage());
    r.child(AppRoutes.appHomeScreen, child: (context) => const HomeScreen());
    r.child(AppRoutes.appServiceOrderPage, child: (context) => ServiceOrderPage(args: r.args.data,));
    r.child(AppRoutes.appServiceOrderListPage, child: (context) => const ServiceOrderListPage());
    r.child(AppRoutes.appPlotsList, child : (context) => PlotsListPage());
    r.child(AppRoutes.appCreateServiceOrderPage, child: (context) => const CreateServiceOrderPage());
    r.child(AppRoutes.appCompanyListPage, child: (context) => CompanyListPage());
    r.child(AppRoutes.appCompanyPage, child: (context) => CompanyPage(args: r.args.data,));
    r.child(AppRoutes.appContractListPage, child: (context) => ContractListPage());
    r.child(AppRoutes.appContractPage, child: (context) => ContractPage(args: r.args.data,));
    r.child(AppRoutes.appEmployeesListPage, child: (context) => EmployeesListPage());
    r.child(AppRoutes.appEmployeePage, child: (context) => EmployeePage(args: r.args.data,));
    r.child(AppRoutes.appFarmListPage, child: (context) => FarmListPage());
    r.child(AppRoutes.appFarmPage, child: (context) => FarmPage(args: r.args.data,));
    r.child(AppRoutes.appMachineryListPage, child: (context) => MachineryListPage());
    r.child(AppRoutes.appMachineryPage, child: (context) => MachineryImplementsPage(args: r.args.data,));
    r.child(AppRoutes.appApprovalsListPage, child: (context) => ApprovalsListPage());
    r.child(AppRoutes.appApprovalsPurchaseRequestDetailPage, child: (context) => ApprovalsPurchaseRequestDetailPage(args: r.args.data,));
    r.child(AppRoutes.appApprovalsServiceOrderDetailPage, child: (context) => ApprovalsServiceOrderDetailPage(args: r.args.data,));

    r.child(AppRoutes.appPurchaseRequestListPage, child: (context) => PurchaseRequestListPage());
    super.routes(r);
  }
}