// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo58SzwMIyFHI4kyOUrXIrntabjPVa1Kg',
    appId: '1:470444987138:web:d34c155ad65a77e493e81b',
    messagingSenderId: '470444987138',
    projectId: 'ezagro-17f15',
    authDomain: 'ezagro-17f15.firebaseapp.com',
    storageBucket: 'ezagro-17f15.firebasestorage.app',
    measurementId: 'G-RVNH12F9LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5yjKVKtJTcKOdHtN_mt1Tnfu1LQkkMGQ',
    appId: '1:470444987138:android:bbb63c47e4823b6093e81b',
    messagingSenderId: '470444987138',
    projectId: 'ezagro-17f15',
    storageBucket: 'ezagro-17f15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAibWM-guIfJcDGH24Xm-R1JQoKXF1b8MM',
    appId: '1:470444987138:ios:c12c997b8059c75093e81b',
    messagingSenderId: '470444987138',
    projectId: 'ezagro-17f15',
    storageBucket: 'ezagro-17f15.firebasestorage.app',
    iosBundleId: 'br.com.ezsolucoes.newEzagroFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAibWM-guIfJcDGH24Xm-R1JQoKXF1b8MM',
    appId: '1:470444987138:ios:c12c997b8059c75093e81b',
    messagingSenderId: '470444987138',
    projectId: 'ezagro-17f15',
    storageBucket: 'ezagro-17f15.firebasestorage.app',
    iosBundleId: 'br.com.ezsolucoes.newEzagroFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo58SzwMIyFHI4kyOUrXIrntabjPVa1Kg',
    appId: '1:470444987138:web:07e915f0a14659e993e81b',
    messagingSenderId: '470444987138',
    projectId: 'ezagro-17f15',
    authDomain: 'ezagro-17f15.firebaseapp.com',
    storageBucket: 'ezagro-17f15.firebasestorage.app',
    measurementId: 'G-MSWVD6F170',
  );

}